ALTER TABLE estimates ADD COLUMN IF NOT EXISTS contract_number VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS contract_date DATE;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS discount_percent NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS discount_amount NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS subtotal_amount NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS room_id INTEGER;
ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS room_name VARCHAR(255) NOT NULL DEFAULT '';
