ALTER TABLE estimates ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft';
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS revision_number INTEGER NOT NULL DEFAULT 1;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id);

ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS category VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS subcategory VARCHAR(255) NOT NULL DEFAULT '';
