ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS meta_keywords TEXT DEFAULT '';
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS og_image TEXT DEFAULT '';
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS seo_region VARCHAR(255) DEFAULT '';