ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS ogrn VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS kpp VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS director_position VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS director_name VARCHAR(255) NOT NULL DEFAULT '';